export const rolePermissions = {
  superadmin: [
    "profile",
    "analytics",
    "payment",
    "company",
    "store",
    "sales",
    "sales_campaign",
    "product",
    "item_campaign",
    "extras",
    "size",
    "order_cust",
    "order",
    "user",
    "kasir",
    "type",
    "stock",
    "pembelian",
    "pembelian_list",
    "report",
    "category_product",
  ],
  admin: [
    "profile",
    "analytics",
    "payment",
    "store",
    "sales",
    "sales_campaign",
    "product",
    "item_campaign",
    "extras",
    "size",
    "order",
    "stock",
    "pembelian",
    "pembelian_list",
    "report",
    "category_product",
  ],
  manajer: [
    "profile",
    "analytics",
    "report",
    "payment",
    "sales",
    "sales_campaign",
    "product",
    "item_campaign",
    "extras",
    "size",
    "order_cust",
    "order",
  ],
  kasir: ["profile", "order_cust", "sales", "kasir"],
  guest: ["profile"], // Only "profile" is accessible when numericRole is null
};
